test: &default

  # Credentials for REST APIs
  client_id: <%= ENV["client_id"] %>
  client_secret: <%= ENV["client_secret"] %>
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username:<%= ENV["username"] %>
  password: <%= ENV["password"] %>
  signature: <%= ENV["signature"] %>
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
