test: &default

  # Credentials for REST APIs
  #client_id: Af5tRlU4SL1-RUX3PboD5f439Jv6FITjfbdyAilQOCtHmVXWahLpryqONS1aNrGGyIZDwqEFBC-xO1V-
  #EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  #client_secret: EPEcwCS3ahvadiKrjfyetAj7xuswXUVgsTqxR6IDflD1PYy9XCeb0Jevs-I_SGr6gk1PU8zD3FRUAigP
  #EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T

  # username: play-facilitator_api1.503estudio.com #play-facilitator_api1.503estudio.com 
  # password: GJKDZNAKA6XCM4WU
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AOHv7TkRIsgZHonFEm8-PQvl3rv5

  # # cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

  # # # IP Address
  # # ip_address: 127.0.0.1
  # # # HTTP Proxys
  # # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
