test: &default

  # Credentials for REST APIs
  client_id:
  #EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: 
  #EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode:

  # Credentials for Classic APIs
  app_id:
  username: 
  password: 
  signature: 
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: 

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode:
