test: &default

  # Credentials for REST APIs
  client_id: Af5tRlU4SL1-RUX3PboD5f439Jv6FITjfbdyAilQOCtHmVXWahLpryqONS1aNrGGyIZDwqEFBC-xO1V-
  #EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EPEcwCS3ahvadiKrjfyetAj7xuswXUVgsTqxR6IDflD1PYy9XCeb0Jevs-I_SGr6gk1PU8zD3FRUAigP
  #EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: raphael-merchant_api1.yopmail.com#jb-us-seller_api1.paypal.com
  password: DSG6J3PTJWT7DZRE#WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A5TPSI8qGZk7blHforpDc5YFk837#AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
