# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5443ede25c5990ab76a0b186d9c1ba26bee13c6b4668f53fd8d02e236cc02b54b7dee9b426ace29e8c23c9e409c9c1bd21bf3b31770a6774d7365edb2355623

test:
  secret_key_base: 352cae75183e3bdea0806dbb72937ac04a6742cb59123a270010cc8acc40dee4cc2d81c4e95505d293d673fc6be753a8bfe7b165551815382ca46e2490e225c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
